### ISSUE TITLE
Figure1.m

### ISSUE THREAD

**Issue by ghost** [VC2015/DMLonGitHub#2]
To whom it may concern,

In the file 'figure1.m', you are using a function called iid_se however this function seems to be undefined.
Could you please indicate what this function is doing ?

Thank you
Kind regards

Gectrics

**Comment by Gectrics** [comment]
To whom it may concern, 

In the file 'figure1.m', you are using a function called iid_se however this function seems to be undefined.
Could you please indicate what this function is doing ? 

Thank you 
Kind regards

Gectrics

**Comment by VC2015** [comment]
I've just uploaded iid_se. Apologies for the error! 

-- Victor
